version: '3.7'

services:
  
  mongo:
    image: mongo
    container_name: fampix_mongodb
    restart: always
    volumes:
      - "mongodata:/data/db"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: parithon
      MONGO_INITDB_ROOT_PASSWORD: mslabs.1

  mongo-express:
    image: mongo-express
    container_name: fampix_mongoexpress
    restart: always
    ports:  
      - 8000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: parithon
      ME_CONFIG_MONGODB_ADMINPASSWORD: mslabs.1
    depends_on:
      - mongo

volumes:
  mongodata: